netreconlab/parse-hipaa

docker-compose.yml
parse/cloud/main.js

Allergies field in Patient should be an arrary instead of string

---

parse/cloud/main.js
parse/index.js

Minor changes to fields such as removing previous/next version pointers.

Update fields for latest CareStore

---

.github/workflows/docker-publish.yml

Push to docker hub on commit

---

docker-compose.mongo.yml
docker-compose.no.hipaa.yml
docker-compose.yml
parse/Dockerfile

Use netrecon images until parse-server images are updated

Switch to netrecon images

---

parse/index.js

Make the loginError displayed on the OCKSample app consistent with the checks performed.

Update loginError message

---

parse/Dockerfile

Builds from Parse `5.0.0-beta.3`

Build from latest beta

---

README.md
docker-compose.yml
parse/cloud/main.js
parse/index.js

refactor: improve javascript

---

parse/index.js

Add a database index for `Patient.remoteID`

feat: add index for remoteID

---

README.md
postgres/Dockerfile
postgres/scripts/parse_idempotency_delete_expired_records.sh
postgres/scripts/setup-parse-index.sh

Adds scripts and information about Idempotency to README.

Update Postgres Indexs

---

docker-compose.yml
parse/Dockerfile
parse/index.js

Update default indexes

---

.slugignore
README.md
app.json
dashboard/Dockerfile.heroku
heroku.yml
parse/index.js

feat: add Heroku deployment button

---

README.md
app.json
docker-compose.mongo.yml
docker-compose.no.hipaa.yml
docker-compose.yml
heroku.yml
parse/index.js

feat: add more config to server

---

app.json
docker-compose.mongo.yml
docker-compose.no.hipaa.yml
docker-compose.yml
heroku.yml
parse/Dockerfile
parse/ecosystem.config.js
parse/scripts/wait-for-postgres.sh

feat: use pm2 in cluster mode

---

parse/Dockerfile

add mailgun and set tag

---

app.json
docker-compose.mongo.yml
docker-compose.no.hipaa.yml
docker-compose.yml
parse/index.js

fix dashboard image

---

heroku.yml

Don't run PM2 on Heroku by default

do not use pm2

---

docker-compose.mongo.yml
docker-compose.no.hipaa.yml
docker-compose.yml
parse/Dockerfile

Update to Parse Server and Dashboard

---

parse/Dockerfile

Changes Parse docker image to latest

Bump to Parse Server 5.4

---

app.json

Use Heroku Postgres paid plan

---

app.json
parse/index.js

allow the ability to modify max file upload

---

parse/Dockerfile

fix: npm warnings in docker build

---

parse/Dockerfile

Attempt to reduce image size as much as possible

install production only

---

.github/workflows/release.yml
docker-compose.yml
parse/index.js

improve dashboard

---

README.md
docker-compose.yml
parse/Dockerfile

add singularity to readme

---

.github/workflows/build-slim.yml
.github/workflows/build.yml
.github/workflows/release-slim.yml
.github/workflows/release.yml
README.md
Singularity
docker-compose.slim.yml
parse/Dockerfile.slim

add slim builds and improve current

---

.github/workflows/build-dashboard.yml
.github/workflows/build.yml
.github/workflows/release-dashboard.yml
.github/workflows/release.yml

fix Singularity images

---

.github/workflows/build-dashboard.yml
.github/workflows/build.yml
.github/workflows/release-dashboard.yml

fix tagging Singularity

---

parse/index.js

Add support for new version of CareKit and ParseCareKit

feat: Add support for RevisionRecord

---

.github/workflows/release.yml
parse/Dockerfile
parse/Dockerfile.dashboard

feat: Add Segment analytics

---

.github/workflows/build-dashboard.yml
.github/workflows/build.yml
.github/workflows/release-dashboard.yml
.github/workflows/release.yml

fix: Remove docker platforms arm/v6 and arm/v7

---

parse/Dockerfile
parse/Dockerfile.dashboard

fix: Update dependencies

---

.github/workflows/release.yml
parse/Dockerfile
parse/Dockerfile.dashboard

fix: Update npm dependencies to latest

---

parse/Dockerfile
parse/Dockerfile.dashboard

feat: Prepare for 8.0.0 release
